### ISSUE TITLE
The Great Dockerfile Cleanup

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/common#67]
**Problem** -- our system of dockerfiles and the things that build them are too complicated. The delta between when we push code and when something breaks needs to be reduced to the minimum possible threshold.

**Solution** -- rearrange our docker image building system to conform to the following. 

- [x] remove all Dockerfiles from this repo except for `base` and `build`. @AFDudley (and, later, the Ops team) will maintain responsibility for those images. They should be tested via Jenkins when code is pushed or when Jenkins is triggered by relevant team member.
- [x] move the Dockerfiles for `data` and `ipfs` to cli. Since cli will be versioning these and is already building `data` the Dockerfiles should be in that repository where they will be well tested. @pietv and @zramsay will maintain responsibility for these images and will ensure that cli properly tests them. They will be built as part of cli's test sequence and pushed upon passing.
- [x] move all third-party Dockerfiles to https://github.com/eris-ltd/eris-services in a `docker` directory. We should have Jenkins run these on a nightly build for now and will add a test sequence with minimum gaurantees for the images themselves.

**Comment by AFDudley** [comment]
I have created develop branches in common and eris-services
I have created a `common_67` branch in common, eris-services, and eris-cli, which contains all of the dockerfile moves and some directory re-organization in anticipation of applying this same process to the ARM side.

**Comment by AFDudley** [comment]
we should just remove the dockerfiles from this repo completely, and put them in an ops- repo.
